# From survey:::.onLoad (may not need all options)
.onLoad <- function (...) {
  if (is.null(getOption("survey.lonely.psu")))
    options(survey.lonely.psu = "fail")
  if (is.null(getOption("survey.ultimate.cluster")))
    options(survey.ultimate.cluster = FALSE)
  if (is.null(getOption("survey.want.obsolete")))
    options(survey.want.obsolete = FALSE)
  if (is.null(getOption("survey.adjust.domain.lonely")))
    options(survey.adjust.domain.lonely = FALSE)
  if (is.null(getOption("survey.drop.replicates")))
    options(survey.drop.replicates = TRUE)
  if (is.null(getOption("survey.multicore")))
    options(survey.multicore = FALSE)
  if (is.null(getOption("survey.replicates.mse")))
    options(survey.replicates.mse = FALSE)
}
